apiVersion: v1
kind: Service
metadata:
  name: syklab-green
  namespace: syklab
spec:
  selector:
    app: syklab
    version: green
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
