apiVersion: v1
kind: Service
metadata:
  name: syklab-canary
  namespace: syklab
  labels:
    app: syklab
spec:
  selector:
    app: syklab
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

