apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: syklab-dr
  namespace: syklab
spec:
  host: syklab-canary.syklab.svc.cluster.local
  subsets:
    - name: blue
      labels:
        version: blue
    - name: green
      labels:
        version: green
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: canary-vs
  namespace: syklab
spec:
  hosts:
    - syklab.dev.kubelancer.net
  gateways:
    - syklab-gateway
  http:
    - route:
        - destination:
            host: syklab-canary.syklab.svc.cluster.local
            subset: blue
          weight: 100
        - destination:
            host: syklab-canary.syklab.svc.cluster.local
            subset: green
          weight: 0

